import type { VercelRequest, VercelResponse } from '@vercel/node';

function cors(res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  cors(res);
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST')   return res.status(405).json({ ok:false, errors:['Use POST'] });

  const { token, repoName, description, isPrivate } = (req.body ?? {}) as Record<string,unknown>;

  if (!token || typeof token !== 'string')
    return res.status(400).json({ ok:false, errors:['GitHub token required'] });
  if (!repoName || typeof repoName !== 'string')
    return res.status(400).json({ ok:false, errors:['repoName required'] });

  try {
    // Get authenticated user first
    const meRes = await fetch('https://api.github.com/user', {
      headers: { Authorization: `Bearer ${token}`, 'User-Agent': 'AppForge/2.0' },
    });
    if (!meRes.ok) return res.status(401).json({ ok:false, errors:['Invalid GitHub token'] });
    const me = await meRes.json() as { login: string };

    // Create repo
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization:  `Bearer ${token}`,
        'Content-Type': 'application/json',
        'User-Agent':   'AppForge/2.0',
      },
      body: JSON.stringify({
        name:         repoName,
        description:  description ?? 'Generated by AppForge — AI multi-language app builder',
        private:      isPrivate ?? false,
        auto_init:    false,
        has_issues:   true,
        has_projects: false,
        has_wiki:     false,
      }),
    });

    const data = await createRes.json() as { html_url?: string; message?: string; clone_url?: string };

    if (!createRes.ok) {
      return res.status(createRes.status).json({
        ok:false,
        errors: [data.message ?? 'GitHub API error'],
      });
    }

    return res.status(201).json({
      ok:    true,
      data: {
        repoName,
        owner:     me.login,
        htmlUrl:   data.html_url,
        cloneUrl:  data.clone_url,
        fullName:  `${me.login}/${repoName}`,
        createdAt: new Date().toISOString(),
      },
    });
  } catch(e) {
    return res.status(500).json({ ok:false, errors:[`GitHub error: ${e instanceof Error?e.message:e}`] });
  }
}
